from get_connection import get_connection
from backend.functions.create_forms_table import create_forms_table
from get_fedex_number import get_fedex_number

forms_data = [
    {
        "sender": "Mike Brown",
        "sender_country": "United States",
        "sender_city": "New York",
        "sender_street": "Broadway",
        "sender_houseNumber": "123",
        "sender_zipCode": "10001",
        "sender_email": "mike.brown@example.com",
        "sender_phoneNumber": "555-1234",
        "recipient": "Ivan Petrov",
        "recipient_country": "Russia",
        "recipient_city": "Moscow",
        "recipient_street": "Tverskaya Street",
        "recipient_houseNumber": "789",
        "recipient_zipCode": "103073",
        "recipient_email": "ivan.petrov@example.com",
        "recipient_phoneNumber": "7-495-678-9012",
        "shippingForm_addressInput": "Red Square, Moscow",
        "paymentForm_contactAfter": True,
        "paymentForm_acceptRules": True,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "Eva Müller",
        "sender_country": "Germany",
        "sender_city": "Berlin",
        "sender_street": "Alexanderplatz",
        "sender_houseNumber": "234",
        "sender_zipCode": "10178",
        "sender_email": "eva.muller@example.com",
        "sender_phoneNumber": "49-30-5678-1234",
        "recipient": "Svetlana Ivanova",
        "recipient_country": "Russia",
        "recipient_city": "Saint Petersburg",
        "recipient_street": "Nevsky Prospect",
        "recipient_houseNumber": "789",
        "recipient_zipCode": "190000",
        "recipient_email": "svetlana.ivanova@example.com",
        "recipient_phoneNumber": "7-812-345-6789",
        "shippingForm_addressInput": "123 Griboedova Canal Embankment, Saint Petersburg",
        "paymentForm_contactAfter": False,
        "paymentForm_acceptRules": True,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "Ivan Petrov",
        "sender_country": "Russia",
        "sender_city": "Moscow",
        "sender_street": "Tverskaya Street",
        "sender_houseNumber": "456",
        "sender_zipCode": "101000",
        "sender_email": "ivan.petrov@example.com",
        "sender_phoneNumber": "7-495-678-9012",
        "recipient": "Emily Davis",
        "recipient_country": "Australia",
        "recipient_city": "Sydney",
        "recipient_street": "George Street",
        "recipient_houseNumber": "987",
        "recipient_zipCode": "2000",
        "recipient_email": "emily.davis@example.com",
        "recipient_phoneNumber": "61-2-8765-4321",
        "shippingForm_addressInput": "456 High St, Anothercity",
        "paymentForm_contactAfter": False,
        "paymentForm_acceptRules": True,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "Alexei Ivanov",
        "sender_country": "Russia",
        "sender_city": "St. Petersburg",
        "sender_street": "Nevsky Prospect",
        "sender_houseNumber": "123",
        "sender_zipCode": "190000",
        "sender_email": "alexei.ivanov@example.com",
        "sender_phoneNumber": "7-812-345-6789",
        "recipient": "Javier González",
        "recipient_country": "Spain",
        "recipient_city": "Barcelona",
        "recipient_street": "La Rambla",
        "recipient_houseNumber": "987",
        "recipient_zipCode": "08002",
        "recipient_email": "javier.gonzalez@example.com",
        "recipient_phoneNumber": "34-93-5678-9012",
        "shippingForm_addressInput": "123 Plaça de Catalunya, Barcelona",
        "paymentForm_contactAfter": True,
        "paymentForm_acceptRules": False,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "David Miller",
        "sender_country": "Germany",
        "sender_city": "Berlin",
        "sender_street": "Friedrichstrasse",
        "sender_houseNumber": "456",
        "sender_zipCode": "10117",
        "sender_email": "david.miller@example.com",
        "sender_phoneNumber": "49-30-7890-1234",
        "recipient": "Dmitri Ivanov",
        "recipient_country": "Russia",
        "recipient_city": "Saint Petersburg",
        "recipient_street": "Nevsky Prospect",
        "recipient_houseNumber": "789",
        "recipient_zipCode": "190000",
        "recipient_email": "dmitri.ivanov@example.com",
        "recipient_phoneNumber": "7-812-678-9012",
        "shippingForm_addressInput": "789 Winter Palace, Saint Petersburg",
        "paymentForm_contactAfter": True,
        "paymentForm_acceptRules": False,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "Olga Ivanova",
        "sender_country": "Russia",
        "sender_city": "Moscow",
        "sender_street": "Red Square",
        "sender_houseNumber": "456",
        "sender_zipCode": "101000",
        "sender_email": "olga.ivanova@example.com",
        "sender_phoneNumber": "7-495-123-4567",
        "recipient": "Hans Schmidt",
        "recipient_country": "Germany",
        "recipient_city": "Munich",
        "recipient_street": "Marienplatz",
        "recipient_houseNumber": "789",
        "recipient_zipCode": "80331",
        "recipient_email": "hans.schmidt@example.com",
        "recipient_phoneNumber": "49-89-2345-6789",
        "shippingForm_addressInput": "789 Viktualienmarkt, Munich",
        "paymentForm_contactAfter": True,
        "paymentForm_acceptRules": True,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "Dmitry Petrov",
        "sender_country": "Russia",
        "sender_city": "Saint Petersburg",
        "sender_street": "Nevsky Prospect",
        "sender_houseNumber": "101",
        "sender_zipCode": "190000",
        "sender_email": "dmitry.petrov@example.com",
        "sender_phoneNumber": "7-812-345-6789",
        "recipient": "Svetlana Kuznetsova",
        "recipient_country": "Russia",
        "recipient_city": "Novosibirsk",
        "recipient_street": "Lenin Street",
        "recipient_houseNumber": "202",
        "recipient_zipCode": "630000",
        "recipient_email": "svetlana.kuznetsova@example.com",
        "recipient_phoneNumber": "7-383-987-6543",
        "shippingForm_addressInput": "303 Karl Marx Avenue, Novosibirsk",
        "paymentForm_contactAfter": False,
        "paymentForm_acceptRules": True,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "Ivan Ivanov",
        "sender_country": "Russia",
        "sender_city": "Moscow",
        "sender_street": "Arbat Street",
        "sender_houseNumber": "303",
        "sender_zipCode": "119002",
        "sender_email": "ivan.ivanov@example.com",
        "sender_phoneNumber": "7-495-678-9012",
        "recipient": "Elena Smirnova",
        "recipient_country": "Russia",
        "recipient_city": "Kazan",
        "recipient_street": "Bauman Street",
        "recipient_houseNumber": "404",
        "recipient_zipCode": "420111",
        "recipient_email": "elena.smirnova@example.com",
        "recipient_phoneNumber": "7-843-123-4567",
        "shippingForm_addressInput": "505 Kremlin Street, Kazan",
        "paymentForm_contactAfter": True,
        "paymentForm_acceptRules": False,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "Sophie Müller",
        "sender_country": "Germany",
        "sender_city": "Munich",
        "sender_street": "Marienplatz",
        "sender_houseNumber": "55",
        "sender_zipCode": "80331",
        "sender_email": "sophie.mueller@example.com",
        "sender_phoneNumber": "49-89-1234-5678",
        "recipient": "Ivan Petrov",
        "recipient_country": "Russia",
        "recipient_city": "Moscow",
        "recipient_street": "Tverskaya Street",
        "recipient_houseNumber": "456",
        "recipient_zipCode": "101000",
        "recipient_email": "ivan.petrov@example.com",
        "recipient_phoneNumber": "7-495-876-5432",
        "shippingForm_addressInput": "Red Square, Moscow",
        "paymentForm_contactAfter": True,
        "paymentForm_acceptRules": True,
        "fedExNumber": get_fedex_number()
    },
    {
        "sender": "Elena Petrova",
        "sender_country": "Russia",
        "sender_city": "Saint Petersburg",
        "sender_street": "Nevsky Prospect",
        "sender_houseNumber": "101",
        "sender_zipCode": "190000",
        "sender_email": "elena.petrova@example.com",
        "sender_phoneNumber": "7-812-345-6789",
        "recipient": "Carlos Sanchez",
        "recipient_country": "Spain",
        "recipient_city": "Barcelona",
        "recipient_street": "La Rambla",
        "recipient_houseNumber": "234",
        "recipient_zipCode": "08001",
        "recipient_email": "carlos.sanchez@example.com",
        "recipient_phoneNumber": "34-93-456-7890",
        "shippingForm_addressInput": "Plaça de Catalunya, Barcelona",
        "paymentForm_contactAfter": False,
        "paymentForm_acceptRules": True,
    "fedExNumber": get_fedex_number()
    }
]


create_forms_table()
connection = get_connection()


def add_data():
    connection = get_connection()

    with connection.cursor() as cursor:
        cursor.execute("USE globalpost")

        for formData in forms_data:
            cursor.execute(
                """
                INSERT INTO forms (
                    sender,
                    sender_country,
                    sender_city,
                    sender_street,
                    sender_houseNumber,
                    sender_zipCode,
                    sender_email,
                    sender_phoneNumber,
                    recipient,
                    recipient_country,
                    recipient_city,
                    recipient_street,
                    recipient_houseNumber,
                    recipient_zipCode,
                    recipient_email,
                    recipient_phoneNumber,
                    shippingForm_addressInput,
                    paymentForm_contactAfter,
                    paymentForm_acceptRules,
                    parcel_fedExNumber
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
                """,
                (
                    formData["sender"],
                    formData["sender_country"],
                    formData["sender_city"],
                    formData["sender_street"],
                    formData["sender_houseNumber"],
                    formData["sender_zipCode"],
                    formData["sender_email"],
                    formData["sender_phoneNumber"],
                    formData["recipient"],
                    formData["recipient_country"],
                    formData["recipient_city"],
                    formData["recipient_street"],
                    formData["recipient_houseNumber"],
                    formData["recipient_zipCode"],
                    formData["recipient_email"],
                    formData["recipient_phoneNumber"],
                    formData["shippingForm_addressInput"],
                    formData["paymentForm_contactAfter"],
                    formData["paymentForm_acceptRules"],
                    formData["fedExNumber"],
                ),
            )

    connection.commit()
    connection.close()


add_data()